print("Hello World!!!!")
print(5)
print("Bye!")
print(13*43)
print("----------Poem-----------")
print("Twinkle Twinkle Little Star")
print("How I wonder what you are")
print("Up above the world so high")
print("Like a diamond in the sky")